/*
# Initial schema for AURA Med Spa

Tables: bookings, subscribers, profiles (for future auth).
RLS policies are permissive until Phase 2 auth — tighten SELECT/UPDATE to ADMIN role then.
*/

-- Bookings
CREATE TABLE IF NOT EXISTS bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  treatment TEXT NOT NULL,
  branch TEXT NOT NULL,
  price NUMERIC(10, 2) NOT NULL,
  booking_date DATE NOT NULL,
  booking_time TEXT NOT NULL,
  notes TEXT,
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'confirmed', 'completed', 'cancelled')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_bookings_created_at ON bookings (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_bookings_branch_date ON bookings (branch, booking_date);

-- Newsletter leads
CREATE TABLE IF NOT EXISTS subscribers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  source TEXT NOT NULL DEFAULT 'footer',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Admin profiles (linked to Supabase Auth in Phase 2)
CREATE TABLE IF NOT EXISTS profiles (
  id UUID PRIMARY KEY REFERENCES auth.users (id) ON DELETE CASCADE,
  email TEXT,
  role TEXT NOT NULL DEFAULT 'USER' CHECK (role IN ('USER', 'ADMIN')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE subscribers ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

-- Temporary open policies (replace with role-based rules when /login ships)
CREATE POLICY "bookings_insert_public"
  ON bookings FOR INSERT TO anon, authenticated
  WITH CHECK (true);

CREATE POLICY "bookings_select_public"
  ON bookings FOR SELECT TO anon, authenticated
  USING (true);

CREATE POLICY "bookings_update_public"
  ON bookings FOR UPDATE TO anon, authenticated
  USING (true);

CREATE POLICY "subscribers_insert_public"
  ON subscribers FOR INSERT TO anon, authenticated
  WITH CHECK (true);

CREATE POLICY "subscribers_select_public"
  ON subscribers FOR SELECT TO anon, authenticated
  USING (true);

CREATE POLICY "profiles_select_own"
  ON profiles FOR SELECT TO authenticated
  USING (auth.uid() = id);
